
services:
  - type: web
    name: krblmsnamuwikis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "python init_db.py && gunicorn app:app --bind 0.0.0.0:$PORT"
